name: MCDBridge
version: 1.1.0
author: Wcash
main: com.Wcash.MCDBridge
api-version: 1.16
website: https://www.github.com/DoubleYouCash/MCDBridge
softdepend: [PermissionsEx]

commands:
  mcdb:
    description: Main MCDBridge Command
    usage: /mcdb (command) [arg1] [arg2]...
    permission: mcdb.main
    permission-message: §f[§9MCDBridge§f]§c You don't have permission to use this command!

permissions:
  mcdb.*:
    description: Gives access to all MCDBridge commands
    children:
      mcdb.reload: true
      mcdb.update: true
  mcdb.command.reload:
    description: Allows to reload the plugin and config files
    default: op
  mcdb.update:
    description: Allows a user to see if the plugin has updates on login
    default: op
  mcdb.command.retrolink:
    description: Retroactively sends messages to all users within the specified roles asking if they would like to receive the rewards
    default: op