name: MCDBridge
version: 0.0.1-ALPHA
author: Wcash
main: com.Wcash.MCDBridge
api-version: 1.16
website: https://github.com/DoubleYouCash/MCDBridge
commands:
  mcdb:
    description: Main MCDBridge Command
    usage: /mcdb (command) [arg1] [arg2]...
    permission: mcdb.main
    permission-message: §f[§9MCDBridge§f]§c You don't have permission to use this command!