name: MCDBridge
version: 1.0.1
author: Wcash
main: com.Wcash.MCDBridge
api-version: 1.16
website: https://github.com/DoubleYouCash/MCDBridge

commands:
  mcdb:
    description: Main MCDBridge Command
    usage: /mcdb (command) [arg1] [arg2]...
    permission: mcdb.main
    permission-message: §f[§9MCDBridge§f]§c You don't have permission to use this command!

permissions:
  mcdb.*:
    description: Gives access to all MCDBridge commands
    children:
      mcdb.reload: true
      mcdb.update: true
  mcdb.reload:
    description: Allows to reload the plugin and config files
    default: op
  mcdb.update:
    description: Allows a user to see if the plugin has updates on login
    default: op